version: '3'

vars:
    RUN: pnpm exec
    BUILD_DIR: ./dist
    CACHE_DIR: ./.cache
    ESLINT_CACHE: '{{.CACHE_DIR}}/.eslintcache'
    PRETTIER_CACHE: '{{.CACHE_DIR}}/.prettiercache'

tasks:
    default:
        cmds:
            - task -l
        silent: true
    install:
        desc: Install all dependencies
        cmds:
            - pnpm install
    install:ci:
        desc: Install all dependencies (CI)
        cmds:
            - pnpm install --frozen-lockfile
    typecheck:
        desc: Run TS typecheck
        cmds:
            - '{{.RUN}} tsc'
    build:
        desc: Build TS
        cmds:
            - rm -rf {{.BUILD_DIR}}
            - '{{.RUN}} tsup'
            - rm -rf ./template/node_modules ./template/build
            - cp -r ./template ./dist/template
    run:
        desc: Build & run
        cmds:
            - task: build
            - '{{.BUILD_DIR}}/main.js'
    version:
        desc: Bump version
        cmds:
            - '{{.RUN}} changeset add'
    release:
        desc: Release
        cmds:
            - task: build
            - '{{.RUN}} changeset publish'
    prettier:
        desc: Run Prettier (autofix)
        cmds:
            - '{{.RUN}} prettier --cache --cache-location={{.PRETTIER_CACHE}} --write .'
    prettier:ci:
        desc: Run Prettier (CI)
        cmds:
            - '{{.RUN}} prettier --check .'
